sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t kimhwan/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kimhwan/docker-react-app npm run test -- --coverage

after_success:
  - find . -type f -exec curl -u $FTP_USER:$FTP_PASS ftp://kimhwan.kr/../../var/www/html/docker-react-app/deploy\;

